# Generated by Django 5.2.1 on 2025-05-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='no_of_owners',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
